name: RL OS ISO Generation

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Install needed packages
      run: |
        sudo apt-get update && apt install debootstrap -y
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        wget -q http://http.us.debian.org/debian/pool/main/l/live-build/live-build_20220505_all.deb
        dpkg -i live-build_*_all.deb
        rm -f live-build_*_all.deb

    - name: Make scripts executable
      run: chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/

    - name: Build ISO
      run: sudo ./build.sh etc/terraform.conf

    - uses: actions/upload-artifact@v3.1.0
      with:
        name: Rolling Rhino Remix OS
        path: builds/
